name: Update README

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3

    - name: Show working directory and list files
      run: |
        pwd  # 현재 작업 디렉토리 출력
        ls -al  # 파일 목록 출력

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-leetcode

    - name: Run upload.py
      run: |
        python upload.py  # upload.py가 Algorithm 폴더 안에 있기 때문에 경로를 이렇게 수정

    - name: Commit changes
      run: |
        git config --global user.name 'L-LIFE'
        git config --global user.email 'seodbsk78@gmail.com'
        git add -A
        git commit -am "auto update README.md"

    - name: Push changes
      run: |
        git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
